version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: internet_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
      #entrypoint: ["internet_application", "run", "--host", "0.0.0.0", "--port", "5000"]

